PetShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import *
from rest_framework import routers

#PARA CREAR EL API :

router = routers.DefaultRouter()
router.register('productos', ProductoViewset)
router.register('tipo_productos', TipoProductoViewset)
router.register('cupon', CuponViewset)
router.register('Carrito', CarritoViewset)
router.register('User', UserViewset)



urlpatterns = [
        
        path('', index, name="index"),
        path('index_api/', index_api, name="index_api"),
        path('about/',about,name="about"),
        path('blogSingle/',blogSingle,name="blogSingle"),
        path('blog/',blog,name="blog"),
        path('cart/',cart,name="cart"),
        path('checkout/',checkout,name="checkout"),
        path('checkout/<str:codigo_cupon>/',checkout,name="checkout_cupon"),
        path('contact/',contact,name="contact"),
        path('productSingle/',productSingle,name="productSingle"),
        path('product/',product,name="product"),
        path('wishlist/',historial,name="historial"),
        path('product-details/<int:id>/', product_details, name='product-details'),
        path('seguimiento/', cambiar_estado_seguimiento, name='cambiar_estado_seguimiento'),


        #cosas del carrito
        path('agregar/<id>/', agregar, name='agregar'),
        path('actualizar/<id>/', actualizar, name='actualizar'),
        path('eliminar/<id>/', eliminar, name='eliminar'),

        #cosas de user
        path('register/',register,name="register"),
        path('edit/', edit, name='edit'),
        path('cancelar-suscripcion/', cancelar_suscripcion, name='cancelar_suscripcion'),
        path('eliminar-perfil/', eliminar_perfil, name='eliminar_perfil'),

        #CRUD
        path('add/',add,name="add"),
        path('delate/<id>/', delate, name='delate'),
        path('update/<id>/', update, name='update'),


        #CRUD CUPONES 
        path('crear/', crear_cupon, name='crear_cupon'),
        path('listar/', lista_cupones, name='lista_cupones'),
        path('actualizar_cup/<id>/', actualizar_cupon, name='actualizar_cupon'),
        path('elimina_cup/<id>/', eliminar_cupon, name='eliminar_cupon'), 

        #PATH DE API
        path('api/', include(router.urls)), 

]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class TipoProducto(models.Model):
    descripcion = models.CharField(max_length=25)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.descripcion 



class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.IntegerField()
    stock = models.IntegerField()
    descripcion = models.CharField(max_length=800)
    tipo = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)
    imagen = models.ImageField(null=True,blank=True)
#    created_at = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.nombre
class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

class Contacto(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    mensaje = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
       
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

class Historial(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    total = models.IntegerField()
    fecha = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)


class Suscriptor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    es_suscriptor = models.BooleanField(default=False)
    descuento = models.FloatField(default=5)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

class Cupon(models.Model):
    codigo = models.CharField(max_length=50, unique=True)
    descuento = models.FloatField()
    
    fecha_fin = models.DateField()
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    
class Seguimiento(models.Model):
    ESTADOS_CHOICES = (
        ('validacion', 'Validación'),
        ('preparacion', 'Preparación'),
        ('reparto', 'Reparto'),
        ('entregado', 'Entregado'),
    )

    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    estado = models.CharField(max_length=20, choices=ESTADOS_CHOICES)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)  # Añade este campo

    # otros campos que necesites

    def __str__(self):
        return f'Seguimiento #{self.id} - Producto: {self.producto.nombre} - Usuario: {self.usuario.username}'

core/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User

# crear formulario nasheeeeeeeeeeeeeeeeeeee

class ProductoForm(ModelForm):

    nombre = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Ingrese Nombre"}))
    precio = forms.IntegerField(min_value=0,widget=forms.NumberInput(attrs={"placeholder":"Ingrese Precio"}))
    stock = forms.IntegerField(min_value=0,widget=forms.NumberInput(attrs={"placeholder":"Ingrese Stock"}))
    descripcion = forms.CharField(min_length=10,max_length=800,widget=forms.Textarea(attrs={"rows":4}))    
    
    class Meta:
        
        model = Producto
        #fields = ['nombre','precio','stock','descripcion','tipo']
        fields = '__all__'

        widgets = {
            'vencimiento' : forms.SelectDateWidget(years=range(1940,2024))
        }
class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

class DonationForm(forms.Form):
    donacion = forms.DecimalField(label='Donación', min_value=1000, required=False)

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ('nombre', 'email', 'mensaje')


class CuponForm(forms.ModelForm):
    class Meta:
        model = Cupon
        fields = ['codigo', 'descuento', 'fecha_fin']
        widgets = {
            'fecha_fin': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
        }
    
#creada por reikom 

core/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import *
from .forms import *
from django.db.models import Sum
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from .forms import RegistrationForm
from datetime import datetime
from django.core.exceptions import ObjectDoesNotExist
from rest_framework import viewsets
from .serializers import *
from django.contrib.auth.models import Group
import requests

# Create your views here.
#VIEWSET QUE SE ENCARGA DE INTERCAMBIAR LA DATA
def grupo_requerido(nombre_grupo):
    def decorator(view_fuc):
        @user_passes_test(lambda user: user.groups.filter(name=nombre_grupo).exists())
        def wrapper(request, *arg, **kwargs):
            return view_fuc(request, *arg, **kwargs)
        return wrapper
    return decorator
    
 # @grupo_requerido('cliente')
 # @grupo_requerido('administrador')

class CuponViewset(viewsets.ModelViewSet):
    queryset = Cupon.objects.all()
    serializer_class = CuponSerializer

class ProductoViewset(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer

class TipoProductoViewset(viewsets.ModelViewSet):
    queryset = TipoProducto.objects.all()
    serializer_class =TipoProductoSerializer

class CarritoViewset(viewsets.ModelViewSet):
    queryset = Carrito.objects.all()
    serializer_class =CarritoSerializer

class UserViewset(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class =UserSerializer





#----------------------------#
def index(request):
    categoria_filtrada = request.GET.get('categoria')  # Obtiene el parámetro de la URL llamado 'categoria'

    if categoria_filtrada:
        url_productos = f'http://127.0.0.1:8000/api/productos/?categoria={categoria_filtrada}'
    else:
        url_productos = 'http://127.0.0.1:8000/api/productos/'

    response_productos = requests.get(url_productos)
    data_productos = response_productos.json()

    data = {
        'listado': data_productos,
        'listado3': data_productos[:4]  # Tomar los primeros 3 elementos de la lista
    }

    return render(request, 'core/index.html', data)

###del api prueba 
def index_api(request):
    #realizamos una solicitud al api| que lo copie el demian por si las dudas que me sale distintos capaz
    response = requests.get('http://127.0.0.1:8000/api/productos/')
    response2 = requests.get('https://mindicador.cl/api')
    response3 = requests.get('https://rickandmortyapi.com/api/character')
   #TRANSFORMA EL JSON PARA LEERLO
    data = response.json()
    moneda = response2.json()
    aux = response3.json()
    personaje = aux['results']

    data = {
        'listado': data,
        'moneda': moneda,
        'pj' :personaje,
        
    }
    

    return render(request, 'core/index-api.html', data)

def base(request):
    carrito = Carrito.objects.filter(usuario=request.user)

    context = {
        'carrito': carrito,
    }
    return render(request, 'core/base.html', context)

def about(request):
    return render(request, 'core/about.html')


def blogSingle(request):
    return render(request, 'core/blog-single.html')


def  blog(request):
    return render(request, 'core/blog.html')

@grupo_requerido('cliente')
def cart(request):
    carrito = Carrito.objects.filter(usuario=request.user)
    codigo_cupon = None
    total_general = 0
    sub_total = 0

    for item in carrito:
        total_producto = item.producto.precio * item.cantidad
        total_general += total_producto
        sub_total += total_producto
        item.total_individual = total_producto

    total_descuento = 0

    # Verificar si el usuario es suscriptor
    try:
        suscriptor = Suscriptor.objects.get(user=request.user)
        if suscriptor.es_suscriptor:
            descuento = suscriptor.descuento / 100
            total_descuento = round(total_general * descuento)
            total_general -= total_descuento
    except Suscriptor.DoesNotExist:
        # Manejar el caso cuando no se encuentra el objeto Suscriptor
        pass

    # Verificar si se ha enviado un cupón en el formulario
    if request.method == 'POST':
        codigo_cupon = request.POST.get('codigo_cupon')
        try:
            cupon = Cupon.objects.get(codigo=codigo_cupon)
            descuento_cupon = round(total_general * (cupon.descuento / 100))
            total_descuento += descuento_cupon
            total_general -= descuento_cupon
        except Cupon.DoesNotExist:
            # Manejar el caso cuando no se encuentra el cupón
            pass

    data = {
        'listado': carrito,
        'final_total': total_general,
        'sub_total': sub_total,
        'descuento': total_descuento,
        'codigo_cupon': codigo_cupon,
        
    }
    return render(request, 'core/cart.html', data)
@grupo_requerido('cliente')
def checkout(request, codigo_cupon=None):
    if request.method == 'POST':
        carrito = Carrito.objects.filter(usuario=request.user)
        
        
        for item in carrito:
            producto = item.producto
            cantidad_comprada = item.cantidad

            # Restar la cantidad comprada del stock del producto
            producto.stock -= cantidad_comprada
            producto.save()
            estado_inicial = 'validacion'
            usuario = request.user
            seguimiento = Seguimiento(usuario=usuario, estado=estado_inicial, producto_id= producto.id)
            seguimiento.save()
            # Crear una instancia de Compra para el historial
            historial = Historial(
                usuario=request.user,
                producto=producto,
                cantidad=cantidad_comprada,
                total=item.producto.precio * cantidad_comprada,
                fecha=datetime.now()
            )
            historial.save()

        # Eliminar los productos del carrito
        carrito.delete()



    carrito = Carrito.objects.filter(usuario=request.user)
    total_general = 0
    sub_total = 0

    for item in carrito:
        item.total = item.producto.precio * item.cantidad
        total_general += item.total
        sub_total += item.total

    # Aplicar descuento si el usuario es suscriptor
    total_descuento = 0
    try:
        suscriptor = get_object_or_404(Suscriptor, user=request.user)
        if suscriptor.es_suscriptor:
            descuento = suscriptor.descuento / 100
            total_descuento = round(total_general * descuento)
            total_general -= total_descuento
    except Suscriptor.DoesNotExist:
        # Manejar el caso cuando no se encuentra el objeto Suscriptor
        pass

    # Aplicar descuento del cupón
    if codigo_cupon:
        cupon = get_object_or_404(Cupon, codigo=codigo_cupon)
        descuento_cupon = round(total_general * (cupon.descuento / 100))
        total_descuento += descuento_cupon
        total_general -= descuento_cupon
    response = requests.get('https://mindicador.cl/api/dolar')
    monedas = response.json()
    valor_dolar = monedas['serie'][0]['valor']#valor del dolar actual
    valor_dolar=round(valor_dolar,2)
    valor=round(total_general/valor_dolar)

    data = {
        'carrito': carrito,
        
        'total_general': total_general,
        'sub_total': sub_total,
        'descuento': total_descuento,
        'codigo_cupon': codigo_cupon,
        'valor': valor
    }


    return render(request, 'core/checkout.html',data)

def contact(request):
    return render(request, 'core/contact.html')

def productSingle(request):
    return render(request, 'core/product-single.html')


def product(request):
    tipos_producto = TipoProducto.objects.all()

    tipo_producto = request.GET.getlist('tipo_producto')  # Obtener los tipos seleccionados

    # Construir la URL de la API
    url_api = 'http://127.0.0.1:8000/api/productos/'
    params = {'tipo_producto': tipo_producto}  # Pasar los tipos seleccionados como parámetros

    # Realizar la solicitud a la API y obtener los datos de productos
    response = requests.get(url_api, params=params)
    data_productos = response.json()

    # Crear listas de productos basadas en los datos de la API
    productos = [Producto(
        id=producto['id'],
        tipo=TipoProducto(id=producto['tipo']['id'], descripcion=producto['tipo']['descripcion']),
        nombre=producto['nombre'],
        precio=producto['precio'],
        stock=producto['stock'],
        descripcion=producto['descripcion'],
        imagen=producto['imagen'],
        created_at=producto['created_at'],
        updated_at=producto['updated_at']
    ) for producto in data_productos]

    # Filtrar productos por tipos seleccionados (opcional)
    if tipo_producto:
        productos = [producto for producto in productos if producto.tipo.descripcion in tipo_producto]

    productoAll = productos[:8]
    producto3 = productos[:3]

    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(productoAll, 6)
        productoAll = paginator.page(page)
    except:
        raise Http404

    data = {
        'tipo': tipos_producto,
        'listado': productoAll,
        'listado3': producto3,
        'tipos_seleccionados': tipo_producto, 
        'paginator': paginator,
    }

    return render(request, 'core/product.html', data)




#creado por sebalol
@grupo_requerido('cliente')
def actualizar(request, id):
    if request.method == 'POST':
        nueva_cantidad = request.POST.get('cantidad')
        item = Carrito.objects.get(id=id)
        item.cantidad = nueva_cantidad
        item.save()
        # Puedes agregar mensajes flash o redirigir a otra página después de la actualización
    return redirect('cart')

@grupo_requerido('cliente')
def agregar(request, id):
    if request.method == 'POST':
        cantidad = int(request.POST.get('cantidad', 1))
        

core/templates/core/add-product.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block css%}
<style>
#imagen-preview {
  max-width: 400px;
  max-height: 400px;
}
</style>
{% endblock %}
{% block contenido %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'core/images/portada2.jpg' %});" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text align-items-end justify-content-center">
      <div class="col-md-9 ftco-animate mb-5 text-center">
        <p class="breadcrumbs mb-0"><span class="mr-2"><a href="{% url 'index' %}">Home <i class="fa fa-chevron-right"></i></a></span> <span>Agregar Productos <i class="fa fa-chevron-right"></i></span></p>
        <h2 class="mb-0 bread">Agregar Productos</h2>
      </div>
    </div>
  </div>
</section>

<div class="container mt-5 mb-4">
  <div class="row">
    <div class="col">
      <form action="" method="POST" enctype="multipart/form-data" class="mi-formulario">
        {% csrf_token %}
        <table>
          {{ form|crispy }}
        </table>
        <img id="imagen-preview" src="{{ form.imagen.url }}" alt="Vista previa de la imagen" />
        <br>

        <div class="text-center">
          <input type="submit" class="btn btn-primary text-center w-25" value="Guardar Producto">
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}
{% block js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function(e) {
          $('#imagen-preview').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
      }
    }

    $('#id_imagen').change(function() {
      readURL(this);
    });
  });
</script>

{% if messages %} 
  {% for aux in messages %} 
    <script>
      Swal.fire({
        title: 'Confirmación',
        text: '{{ aux }}',
        icon: 'success',
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Confirmar'
      });
    </script>
  {% endfor %} 
{% endif %}

{% endblock %}

core/templates/core/blog.html
{% extends 'core/base.html' %}
{% load static %}
 

{% block contenido %}  
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'core/images/bg_2.jpg' %});" data-stellar-background-ratio="0.5">
	<div class="overlay"></div>
	<div class="container">
		<div class="row no-gutters slider-text align-items-end justify-content-center">
			<div class="col-md-9 ftco-animate mb-5 text-center">
				<p class="breadcrumbs mb-0"><span class="mr-2"><a href="{% url 'index' %}">Inicio <i class="fa fa-chevron-right"></i></a></span> <span>Blog <i class="fa fa-chevron-right"></i></span></p>
				<h2 class="mb-0 bread">Blog</h2>
			</div>
		</div>
	</div>
</section>

<section class="ftco-section">
	<div class="container">
		<div class="row d-flex">
			<div class="col-lg-6 d-flex align-items-stretch ftco-animate">
				<div class="blog-entry d-md-flex">
					<a href="noticia1.html" class="block-20 img" style="background-image: url({% static 'core/images/image_2.jpg' %});">
					</a>
					<div class="text p-4 bg-light">
						<div class="meta">
							<p><span class="fa fa-calendar"></span> 23 de abril de 2020</p>
						</div>
						<h3 class="heading mb-3"><a href="noticia1.html">La Historia de un Rescate de Animales en Peligro de Extinción</a></h3>
						<p>Un pequeño río llamado Duden fluye cerca de su lugar y lo abastece de la regelialia necesaria.</p>
						<a href="noticia1.html" class="btn-custom">Continuar <span class="fa fa-long-arrow-right"></span></a>
					</div>
				</div>
			</div>
			<div class="col-lg-6 d-flex align-items-stretch ftco-animate">
				<div class="blog-entry d-md-flex">
					<a href="noticia2.html" class="block-20 img" style="background-image: url({% static 'core/images/image_1.jpg' %});">
					</a>
					<div class="text p-4 bg-light">
						<div class="meta">
							<p><span class="fa fa-calendar"></span> 23 de abril de 2020</p>
						</div>
						<h3 class="heading mb-3"><a href="noticia2.html">El Increíble Descubrimiento de una Nueva Especie de Mariposa</a></h3>
						<p>Un pequeño río llamado Duden fluye cerca de su lugar y lo abastece de la regelialia necesaria.</p>
						<a href="noticia2.html" class="btn-custom">Continuar <span class="fa fa-long-arrow-right"></span></a>
					</div>
				</div>
			</div>
			<div class="col-lg-6 d-flex align-items-stretch ftco-animate">
				<div class="blog-entry d-md-flex">
					<a href="noticia3.html" class="block-20 img" style="background-image: url({% static 'core/images/image_3.jpg' %});">
					</a>
					<div class="text p-4 bg-light">
						<div class="meta">
							<p><span class="fa fa-calendar"></span> 23 de abril de 2020</p>
						</div>
						<h3 class="heading mb-3"><a href="noticia3.html">El Rescate de una Familia de Osos en Peligro</a></h3>
						<p>Un pequeño río llamado Duden fluye cerca de su lugar y lo abastece de la regelialia necesaria.</p>
						<a href="noticia3.html" class="btn-custom">Continuar <span class="fa fa-long-arrow-right"></span></a>
					</div>
				</div>
			</div>
			<div class="col-lg-6 d-flex align-items-stretch ftco-animate">
				<div class="blog-entry d-md-flex">
					<a href="noticia4.html" class="block-20 img" style="background-image: url({% static 'core/images/image_4.jpg' %});">
					</a>
					<div class="text p-4 bg-light">
						<div class="meta">
							<p><span class="fa fa-calendar"></span> 23 de abril de 2020</p>
						</div>
						<h3 class="heading mb-3"><a href="noticia4.html">Los Esfuerzos para Proteger el Hábitat de los Elefantes Africanos</a></h3>
						<p>Un pequeño río llamado Duden fluye cerca de su lugar y lo abastece de la regelialia necesaria.</p>
						<a href="noticia4.html" class="btn-custom">Continuar <span class="fa fa-long-arrow-right"></span></a>
					</div>
				</div>
			</div>
			<div class="col-lg-6 d-flex align-items-stretch ftco-animate">
				<div class="blog-entry d-md-flex">
					<a href="noticia5.html" class="block-20 img" style="background-image: url({% static 'core/images/image_5.jpg' %});">
					</a>
					<div class="text p-4 bg-light">
						<div class="meta">
							<p><span class="fa fa-calendar"></span> 23 de abril de 2020</p>
						</div>
						<h3 class="heading mb-3"><a href="noticia5.html">Descubriendo una Nueva Especie de Ave en la Selva Amazónica</a></h3>
						<p>Un pequeño río llamado Duden fluye cerca de su lugar y lo abastece de la regelialia necesaria.</p>
						<a href="noticia5.html" class="btn-custom">Continuar <span class="fa fa-long-arrow-right"></span></a>
					</div>
				</div>
			</div>
			<div class="col-lg-6 d-flex align-items-stretch ftco-animate">
				<div class="blog-entry d-md-flex">
					<a href="noticia6.html" class="block-20 img" style="background-image: url('{% static 'core/images/image_6.jpg' %});">
					</a>
					<div class="text p-4 bg-light">
						<div class="meta">
							<p><span class="fa fa-calendar"></span> 23 de abril de 2020</p>
						</div>
						<h3 class="heading mb-3"><a href="noticia6.html">La Impactante Historia de una Tortuga Rescatada</a></h3>
						<p>Un pequeño río llamado Duden fluye cerca de su lugar y lo abastece de la regelialia necesaria.</p>
						<a href="noticia6.html" class="btn-custom">Continuar <span class="fa fa-long-arrow-right"></span></a>
					</div>
				</div>
			</div>
		</div>
		<div class="row mt-5">
			<div class="col text-center">
				<div class="block-27">
					<ul>
						<li><a href="#">&lt;</a></li>
						<li class="active"><span>1</span></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
						<li><a href="#">&gt;</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>


{% endblock %}

core/templates/core/crear_cupon.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block css %}


{% endblock %}
{% block contenido %}
<section class="hero-wrap hero-wrap-3" style="background-image: url({% static 'core/images/portada2.jpg' %});" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text align-items-end justify-content-center">
      <div class="col-md-9 ftco-animate mb-5 text-center">
    
        <h2 class="mb-0 bread">Crear Cupones</h2>
      </div>
    </div>
  </div>
</section>
<form method="post" class="my-form">
  {% csrf_token %}
  
  {{ form|crispy }}

  <div class="form-group">
    <button type="submit" class="btn btn-primary">Crear cupón</button>
  </div>
</form>

{% endblock %}
{% block js %}



  
{% endblock %}

core/templates/core/lista_cupones.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block css %}


{% endblock %}
{% block contenido %}
<section class="hero-wrap hero-wrap-3" style="background-image: url({% static 'core/images/portada2.jpg' %});" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text align-items-end justify-content-center">
      <div class="col-md-9 ftco-animate mb-5 text-center">
    
        <h2 class="mb-0 bread">Listar Cupones</h2>
      </div>
    </div>
  </div>
</section>
<ul class="cupones-lista">
    {% for cupon in cupones %}
      <li class="cupon-item">
        <div class="cupon-codigo">{{ cupon.codigo }}</div>
        <div class="cupon-descuento">{{ cupon.descuento }}</div>
        <div class="cupon-opciones">
          <a href="{% url 'actualizar_cupon' cupon.id %}">Modificar</a>
          <a onclick="eliminarCupones({{cupon.id}})" class="jijija">Eliminar</a>
        </div>
      </li>
    {% empty %}
      <li class="cupon-item empty">No hay cupones disponibles.</li>
    {% endfor %}
  </ul>
  

{% endblock %}
{% block js %}



  
{% endblock %}